spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usersync?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000

# 自动构建类，mapper等
mybatis-plus:
  global-config:
    db-config:
      db-type: mysql
      #设置逻辑删除的值，通过引用注解@TableLogic来标明字段是逻辑删除
      logic-not-delete-value: 0
      logic-delete-value: 1
  # 配置mapper文件的路径
  mapper-locations: classpath:mapper/*.xml

#日志配置
logging:
  config:
    root: warn
    com.thriteen.bgd.usersync.dao: trace
  pattern:
    #日志输出格式
    console: '%p%m%n'

# 配置交互字符集
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true